# Docker Compose configuration for deployment

networks:
  web:
    external: true

services:
  server:
    build: .
    networks:
      - web
    expose:
      - "80"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.codycolor-client.rule=Host(`codycolor.codyroby.it`)"
      - "traefik.http.routers.codycolor-client.entrypoints=web,websecure"
      - "traefik.http.routers.codycolor-client.middlewares=codycolor-client-redirectscheme"
      - "traefik.http.middlewares.codycolor-client-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.codycolor-client-redirectscheme.redirectscheme.permanent=true"
