version: '3'

vars:
  DC: docker compose -f docker-compose.yml

tasks:
  cmd:
    desc: Show the docker compose command
    cmds:
      - echo 'Docker compose command:'
      - echo '{{.DC}}'

  up:
    desc: Start the CodyColor services
    cmds:
      - '{{.DC}} up -d website server'
      - '{{.DC}} ps'

  rebuild:
    desc: Rebuild and restart the CodyColor client and server
    cmds:
      - '{{.DC}} build website server'
      - '{{.DC}} up -d --force-recreate'

  ps:
    desc: Show running containers
    cmds:
      - '{{.DC}} ps'

  rs:
    desc: Restart all services
    cmds:
      - '{{.DC}} restart'

  stop:
    desc: Stop all services
    cmds:
      - '{{.DC}} stop'

  rm:
    desc: Remove all containers (force, stop)
    cmds:
      - '{{.DC}} rm -fs'
